[package]
name = "discord_status"
version = "0.1.0"
edition = "2024"

[dependencies]
eframe = "0.31.1"
reqwest = { version = "0.12.20", features = ["json"] }
serde = { version = "1.0.219", features = ["derive"] }
tokio = { version = "1.45.1", features = ["full"] }
tokio-tungstenite = "0.27.0"
